language: haskell
branches:
  only:
  - master
env:
  global:
   - secure: "SSDFHpgbgYSKh7iVdfmtgI4B5bq/5ysBGx9BamJp4IJ5WsaApxUik4lhhzwPB5Xr3uWBLCksPQ5LZCi5JxxB+J7qlfKXJLIoAcW1vPb+gxOxNCyeL3ZeC4fZkpfpDZeoWl+tEjFvWWgfse9xM5w48urA6MRjSkKaoP05hnjc6O50d4s0X3Kx+fOazpyPTITtuqh6ZoHRhhPotE6VNuORgu69PYOqElPIL/kI0eDmdsalgl5WxX0hO7dED4ZXc+QGLIXIZv8bub9ysTAXjEliWwmFOsvKt3Gr9GsnQBYoh9q9ecQuzgDE9zb0pZOa/htVsXMhbHvNVvHtcfEybj5j04ro1DdIlbX8NdoI14VaQsO4J/xTesaI59mQ+THqAohZ7H0DPmXl51R9JwZ+w2iVSJKYs+KLaVA7f0pO9MeOJBiIwVQcaNiV8wGJa6m1+ovUamrOX2UIb6qPCGhpD2yUty3+oBWzqKjHlL6SDYLkeJWTBRGgInYrBtsoMZbopgYP4dUVYjJnQoPeDf6jfLIKpDV++Kd50AU8B/VE9bN919chiPLE/P579Sqg0UfVMriIsTx+xsAhnm4a9N1ezYZyCbTtZfj6MJty7skqUOs27KJQXD5VBxv5yrrUClBJd1mY/Z1g3uozksl6rWyU7PuZLEakwI9KPkt2NvDIOX9SkH4="
install:
- cabal sandbox init
  #- cabal install -j hakyll
before_script:
- cd _bin
- git checkout gh-pages
- git pull origin gh-pages
- cd ..
- rm -f /_bin/hakyll-sandbox.tar.gz
script: tar -zcf  ./_bin/hakyll-sandbox.tar.gz ./.cabal-sandbox
after_script:
- cd _bin
- git status
- git add hakyll-sandbox.tar.gz
- git config --global user.email "$GH_EMAIL"
- git config --global user.name "$GH_NAME"
- git commit -m "snapshot $(date '+%m/%d/%y %H:%M')"
- git push "$HAKYLL_SANDBOX_URL" gh-pages >/dev/null 2>&1
- cd ..
